#ifndef PL_PREPROC_H
#define PL_PREPROC_H

#define PL_EAT(...)

#define PL_SCAN(...) __VA_ARGS__

#define PL_PARENS ()

#define PL_IF(B) PL_IIF(B)
#define PL_IIF(B) DETAIL_PL_IIF##B
#define DETAIL_PL_IIF1(...) __VA_ARGS__ PL_EAT
#define DETAIL_PL_IIF0(...) PL_SCAN

#define PL_EVAL(...) DETAIL_PL_EVAL0(DETAIL_PL_EVAL0(DETAIL_PL_EVAL0(DETAIL_PL_EVAL0(__VA_ARGS__))))
#define DETAIL_PL_EVAL0(...) DETAIL_PL_EVAL1(DETAIL_PL_EVAL1(DETAIL_PL_EVAL1(DETAIL_PL_EVAL1(__VA_ARGS__))))
#define DETAIL_PL_EVAL1(...) DETAIL_PL_EVAL2(DETAIL_PL_EVAL2(DETAIL_PL_EVAL2(DETAIL_PL_EVAL2(__VA_ARGS__))))
#define DETAIL_PL_EVAL2(...) DETAIL_PL_EVAL3(DETAIL_PL_EVAL3(DETAIL_PL_EVAL3(DETAIL_PL_EVAL3(__VA_ARGS__))))
#define DETAIL_PL_EVAL3(...) __VA_ARGS__

#define PL_EACH(FUNC, ...) __VA_OPT__(PL_EVAL(DETAIL_PL_EACH_(FUNC, __VA_ARGS__)))
#define DETAIL_PL_EACH_(FUNC, X, ...) FUNC(X) __VA_OPT__(DETAIL_PL_EACH_NEXT PL_PARENS (FUNC, __VA_ARGS__))
#define DETAIL_PL_EACH_NEXT() DETAIL_PL_EACH_

#endif
